### ISSUE TITLE
Redirecionando para localhost:3000/auth/login em produção (vercel)

### ISSUE THREAD

**Issue by paulospiguel** [devdeck101/authjs-prisma-template#2]
Olá, estou usando o templete e depois de alterar alguns estilos fix o deploy na vercel. No tentanto quando tento entrar em uma rota não permitida ser login ele me redireciona (corretamente e o esperado) para a página de login para efetuar o mesmo. Mas o problema é que sempre mostra o http://localhost:3000/auth/login, sendo que deveria mostrar https:<minha-rota-vercel>/auth/login.

Não consegui encontrar nada (configurações de rotas ou middleware) que possa fazer isso estar com este comportamento, mesmo as váriaveis de ambiente da vercel estar tudo configurado como se deve ser.

**Comment by devdeck101** [comment]
Você precisa mudar a variável de ambiente na vercel. Dê uma olhada no arquivo .env . No seu deploy da vercel, vai em configurações/settings -> variáveis e ambiente e muda.

**Comment by paulospiguel** [comment]
Não consigo perceber qual a variavél está a dizer, pois a única que tem mensão no código a url é a NEXT_PUBLIC_URL e está está somente sendo usada na funcionalidade de resend. No caso, refiro-me a middleware que faz o redirecionamento não usando a URL que está deployed mas sim o localhost:3000. 

Fiz um teste localmente com npm run dev -p 3001 e quando tento entrar em uma rota privada mostra o http://localhost:3001/auth/login, mesmo o NEXT_PUBLIC_URL estando como localhost:3000. Provalvelmente não é essa variável, só que preciso setar alguma outra variável que não está no .env, mas acredito que não.

Acredito que é algo neste trecho de código:

![image](https://github.com/devdeck101/authjs-prisma-template/assets/41386612/5ea9cf43-0046-4af8-abaf-14e2ff267523)

Penso que o "req.url" que é responsavel por pegar a url base para depois concatenar com a string para redirecionar, mas não consegui perceber se existe alguma configuração específica ou isso pega de alguma variável.

Minha questão é se conseguiste testar esse projeto em ambiente cloud para saber se o erro é somente do meu lado.

**Comment by devdeck101** [comment]
Close with response
