### ISSUE TITLE
Internacionalização 

### ISSUE THREAD

**Issue by DevIsraelSantos** [devdeck101/authjs-prisma-template#3]
### Sugestão de melhoria: Adicionar integração com `next-intl` para internacionalização

**Descrição:**
Estou criando um PR para corrigir algumas nomenclaturas em inglês do projeto, com o objetivo de melhorar a consistência do idioma e facilitar a manutenção do código. Além disso, acredito que seria uma excelente melhoria integrar uma biblioteca de internacionalização diretamente no template, como o `next-intl`, para oferecer suporte a múltiplos idiomas de maneira nativa.

**Objetivo:**
- Corrigir as nomenclaturas em labels no código do projeto.
- Propor a adição da biblioteca para internacionalização (Ex.:  `next-intl`), permitindo que o template suporte facilmente múltiplos idiomas.

**Próximos passos:**
Estarei trabalhando em uma solução para implementar essa integração enquanto aguardo uma resposta positiva sobre a proposta.

**Benefícios esperados:**
- Maior flexibilidade para suportar novos idiomas no projeto.
- Melhoria na organização e manutenção das traduções.
- Evolução do template para mais casos de uso.

**Comment by devdeck101** [comment]
PR merged. Great job!
